on:
  schedule:
    - cron: '27 4 * * 1' # Run at 4:27 every monday


jobs:
  linkcheck:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.2

      - name: Check links
        run: |
          zola check
